### ISSUE TITLE
[Beta Launcher] Unexpected Error Occured While Running Game Scan 

### ISSUE THREAD

**Issue by jjur** [ProjectCeleste/Celeste.Launcher#82] opened 2020-03-21 10:59 UTC
# Describe the bug
![image](https://user-images.githubusercontent.com/13292381/77224774-e03f6300-6b8e-11ea-8006-0bfabcbe364d.png)

During Game Scan, this error message randomly pop-up. It would be nice, if it can automatically redownload the broken file and continue downloading.

## Log

2020-03-21 16:04:34.894 +05:30 [INF] Initializing bootstrapper
2020-03-21 16:04:34.928 +05:30 [INF] No user config loaded, path D:\Games\AOEO3\CelesteConfig.xml does not exist
2020-03-21 16:04:34.930 +05:30 [INF] Game path set to D:\Games\AOEO3\CelesteConfig.xml
2020-03-21 16:04:34.930 +05:30 [INF] IsSteamVersion: false
2020-03-21 16:04:34.932 +05:30 [INF] Initialized web socket
2020-03-21 16:04:34.932 +05:30 [INF] Initializing fingerprint provider
2020-03-21 16:04:34.935 +05:30 [INF] Bootstrapper initialized
2020-03-21 16:05:08.840 +05:30 [INF] Stored credentials is null: true
2020-03-21 16:05:08.840 +05:30 [INF] Performing login with entered credentials
2020-03-21 16:05:08.875 +05:30 [DBG] Initializing web socket
2020-03-21 16:05:08.904 +05:30 [INF] Attempting to connect to wss://ns544971.ip-66-70-180.net:4513/
2020-03-21 16:05:10.144 +05:30 [DBG] Web socket open
2020-03-21 16:05:10.144 +05:30 [INF] Successfully connected websocket
2020-03-21 16:05:10.610 +05:30 [INF] Login succeeded
2020-03-21 16:05:10.610 +05:30 [INF] User has selected to store new credentials
2020-03-21 16:05:53.236 +05:30 [INF] Preparing to start game, is offline: false
2020-03-21 16:05:53.239 +05:30 [INF] User is online, will perform game scan
2020-03-21 16:05:53.239 +05:30 [INF] Preparing games canner api
2020-03-21 16:05:55.286 +05:30 [INF] Starting quick game scan
2020-03-21 16:05:55.290 +05:30 [INF] Game scanner did not approve game files
2020-03-21 16:08:38.640 +05:30 [ERR] Download was completed (25553792 bytes), but did not receive expected size of 36039552 bytes
System.Exception: Download was completed (25553792 bytes), but did not receive expected size of 36039552 bytes
   at ProjectCeleste.GameFiles.GameScanner.FileDownloader.ChunkFileDownloader.<DownloadAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProjectCeleste.GameFiles.GameScanner.GameScannnerManager.<ScanAndRepairFile>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ProjectCeleste.GameFiles.GameScanner.GameScannnerManager.<ScanAndRepair>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ProjectCeleste.GameFiles.GameScanner.GameScannnerManager.<ScanAndRepair>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Celeste_Launcher_Gui.Windows.GameScannerWindow.<>c__DisplayClass8_0.<<Window_Loaded>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Celeste_Launcher_Gui.Windows.GameScannerWindow.<Window_Loaded>d__8.MoveNext()
2020-03-21 16:11:36.517 +05:30 [INF] Starting quick game scan
2020-03-21 16:11:36.517 +05:30 [INF] Game scanner did not approve game files
2020-03-21 16:26:29.268 +05:30 [ERR] Download was completed (54352526 bytes), but did not receive expected size of 64838286 bytes
System.Exception: Download was completed (54352526 bytes), but did not receive expected size of 64838286 bytes
   at ProjectCeleste.GameFiles.GameScanner.FileDownloader.ChunkFileDownloader.<DownloadAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ProjectCeleste.GameFiles.GameScanner.GameScannnerManager.<ScanAndRepairFile>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ProjectCeleste.GameFiles.GameScanner.GameScannnerManager.<ScanAndRepair>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ProjectCeleste.GameFiles.GameScanner.GameScannnerManager.<ScanAndRepair>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Celeste_Launcher_Gui.Windows.GameScannerWindow.<>c__DisplayClass8_0.<<Window_Loaded>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Celeste_Launcher_Gui.Windows.GameScannerWindow.<Window_Loaded>d__8.MoveNext()
2020-03-21 16:26:44.514 +05:30 [INF] Starting quick game scan
2020-03-21 16:26:44.514 +05:30 [INF] Game scanner did not approve game files

**Comment by martinmine** [comment] 2020-04-08 17:52
I believe this is a rare side-effect for users who is experiencing rate limiting/throttling of connections because of the parallel downloader. I think we should rather use the legacy (serial) downloader and rather put up download mirrors/proxies/caches as it is apparent to me this is not the way to solve the problem of slow game scans. If not, it should be default serial and an opt-in feature to use the parallel downloader. Just to get more info on what type of users experience this, could you let me know your download speed and your ping on i.e. Speedtest?

**Comment by jjur** [comment] 2020-04-12 07:57
Internet speed depends on the server location, but generally it is fast. I am attaching the screenshot
![image](https://user-images.githubusercontent.com/13292381/79063722-f38eab80-7cc0-11ea-8b60-75c8e7a30563.png)

I had to rerun the game scan about 8 times, but It downloaded the game. It would be just nice, if it can restart downloading automatically when it hits an exception and retry for example 3 times.

**Comment by martinmine** [comment] 2020-04-12 09:07
There is already a retry mechanism, the problem is that the server rate-limits and denies connection for a certain amount of time. How long it denies connections entirely depends on the connection and that is what makes this problematic. It is regardless a problem that should be solved by having faster servers/CDNs and not by implementing a parallel downloader.

**Comment by martinmine** [comment] 2020-07-29 19:22
I will give an update on this issue as we have made good progress on this:
- The "fast game scan" (parallel download option) is now a selectable option, which is disabled by default. If selected, the user will get a notification saying that if the download fails, it might be worth disabling this feature (as seen in this case).
- We are going to move the game files behind a CDN which will eliminate the need for this feature in the very near future.

**Comment by martinmine** [comment] 2020-11-01 19:44
We have switched to Cloudflare as our CDN provider a few months ago. A release was just made that removes the "Fast download" option as we get this feature "by design" now instead of having to create ugly hacks to avoid network limitations that in the end bites us in the ass. I will go ahead and close this as the code for the parallel download feature is no longer used.

**Closed by martinmine** 2020-11-01 19:44 UTC
